name: image_editor_pro
description: Image Editor Plugin with simple, easy support for image editing using paints,text and emoji like stories.
version: 1.0.9
homepage: https://github.com/zeeshux7860/Image_editor_pro_package

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.3
  zoom_widget: ^0.2.1
  font_awesome_flutter: ^9.1.0
  image_picker: ^0.8.2
  path_provider: ^2.0.2
  image_gallery_saver: ^1.6.9
  permission_handler: ^8.1.4
  dio: ^4.0.0
  screenshot: ^1.2.3
  signature:
      git:
        url: https://github.com/vickyleu/signature.git
  flutter_colorpicker: any

dev_dependencies:
  pedantic: ^1.9.2

  flutter_test:
    sdk: flutter