name: image_editor_pro
description: Image Editor Plugin with simple, easy support for image editing using paints,text and emoji like stories.
version: 1.0.9
homepage: https://github.com/zeeshux7860/Image_editor_pro_package

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  zoom_widget: ^0.1.3
  font_awesome_flutter: ^8.11.0
  image_picker: ^0.6.7+21
  path_provider: ^1.6.27
  image_gallery_saver: ^1.6.7
  permission_handler: ^5.0.1+1
  dio: ^3.0.10
  screenshot: ^0.2.0
  signature:
    path: /Users/vickyleu/Develop/GitRepo/signature
#      git:
#        url: https://github.com/vickyleu/signature.git
  flutter_colorpicker: ^0.3.5

dev_dependencies:
  pedantic: ^1.9.2

  flutter_test:
    sdk: flutter